---
namespace: community
name: gestion_glasses_role
version: 1.0
readme: README.md
authors:
  - Allan & Brice
description: Gestion glasses role  
license_file: COPYING
tags:
  - v1
repository: https://github.com/brikema/GestionGlasses.git
documentation: https://github.com/brikema/GestionGlasses.git
homepage: https://github.com/brikema/GestionGlasses.git
issues: https://github.com/brikema/GestionGlasses.git
build_ignore:
  - .gitignore
 